Default = "MyDevice"

[[Device]]
Name     = "MyDevice"
IP       = "192.168.178.20"
Port     = 1924
Mac      = "00-11-22-33-44-55"
Username = "usr"
Password = "pass"

[[Device]]
Name     = "Demo"
IP       = "192.168.178.50"
Port     = 1924
Mac      = "00-A1-B2-C3-D4-E5"
Username = "admin"
Password = "admin"

