//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynoCtrl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SynoCtrl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SynologyController.
        ///
        ///Usage:
        ///  synoctrl shutdown [&lt;name&gt;] [options]
        ///  synoctrl reboot [&lt;name&gt;] [options]
        ///  
        ///  synoctrl wol [&lt;name&gt;] [options]
        ///  synoctrl getip [&lt;name&gt;] [options]
        ///  synoctrl getmac [&lt;name&gt;] [options]
        ///  synoctrl ping [&lt;name&gt;] [options]
        ///  
        ///  synoctrl status &lt;status_fields&gt; [&lt;name&gt;] [--info] [options]
        ///  synoctrl status-all [&lt;name&gt;] [--info] [options]
        ///  synoctrl status-list [options]
        ///  
        ///  synoctrl create-config &lt;output_filename&gt; [--override] [options]
        ///  synoctrl -h | --help
        ///  syno [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cmd_schema {
            get {
                return ResourceManager.GetString("cmd_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ################################################################################
        ///#                                                                              #
        ///#  This is the example config file for SynoCtrl                                #
        ///#                                                                              #
        ///#  Edit the config file and copy it to one of these destinations to use it:    #
        ///#      %program_location%\synoctrl.toml                                        #
        ///#      %userprofile% [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config_example {
            get {
                return ResourceManager.GetString("config_example", resourceCulture);
            }
        }
    }
}
